### ISSUE TITLE
Snapcept doesnt work (10.34.5.0)

### ISSUE THREAD

**Issue by FKamikaze** [Snapcept/Snapcept#2]
[xposed_error_20180629_005504.log](https://github.com/Snapcept/Snapcept/files/2147220/xposed_error_20180629_005504.log)
I've installed snapchat 10.34.5.0 Beta and then the mod but it doesnt work.

**Comment by brien1254** [comment]
Didn't work with the beta for me, but the regular version did. http://apk.co/snapchat/snapchat-103450

**Comment by Snapcept** [comment]
The module ONLY works for the version specified, so not for the beta.
