### ISSUE TITLE
Screenshot bypass

### ISSUE THREAD

**Issue by jaktrz** [Snapcept/Snapcept#3]
Hello,
I have a suggestion to add Screenshot Bypass funcionality. There is a class `actw` where is a method `a(LinkedHashMap.class)`. Hooking it with `XC_MethodReplacement.DO_NOTHING` will prevent detecting screenshots by Snapchat. It will be nice if you add this funcionality to app. Sorry for my bad English.
Thank you in advance.

**Comment by georgeravenholm** [comment]
cant you PR it then?

**Comment by GHXST01** [comment]
Was this ever tested / confirmed working?
