### ISSUE TITLE
Merge Or Push My Edit

### ISSUE THREAD

**Issue by ghost** [Snapcept/Snapcept#9]
https://github.com/Juxstin/Snapcept-Edit

It includes a screenshot bypass

**Comment by georgeravenholm** [comment]
you could've forked and pull requested lmao

**Comment by ghost** [comment]
Sadly i'm new to github idk how

**Comment by georgeravenholm** [comment]
basically you click the little fork button at the top which copies it to your github
then you make the changes on your copy and then you make a pull request

doing the fork has it so its like a linked copy
but hey were developers u can just google it heh
